import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "../components/BottomNav";
import SwRegistration from "../components/SwRegistration";
import InstallPrompt from "../components/InstallPrompt";
import AuthListener from "../components/AuthListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="manifest" href="/manifest.json" />
        <main className="app-root">
          <div className="app-container">{children}</div>
        </main>
  <AuthListener />
  <SwRegistration />
  <InstallPrompt />
        <BottomNav />
      </body>
    </html>
  );
}
